# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_7.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import data_send as ds

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ServiceWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.ServiceWidget.setGeometry(QtCore.QRect(10, 0, 781, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ServiceWidget.setFont(font)
        self.ServiceWidget.setObjectName("ServiceWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ServiceWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(2, 2, 761, 511))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.Speed_slider_2 = QtWidgets.QSlider(self.widget)
        self.Speed_slider_2.setProperty("value", 25)
        self.Speed_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_slider_2.setObjectName("Speed_slider_2")
        self.gridLayout_2.addWidget(self.Speed_slider_2, 0, 1, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.Speed_slider_5 = QtWidgets.QSlider(self.widget)
        self.Speed_slider_5.setProperty("value", 25)
        self.Speed_slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_slider_5.setObjectName("Speed_slider_5")
        self.gridLayout_2.addWidget(self.Speed_slider_5, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.Speed_slider = QtWidgets.QSlider(self.widget)
        self.Speed_slider.setProperty("value", 25)
        self.Speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_slider.setObjectName("Speed_slider")
        self.gridLayout_2.addWidget(self.Speed_slider, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.Step_slider = QtWidgets.QSlider(self.widget)
        self.Step_slider.setProperty("value", 35)
        self.Step_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Step_slider.setObjectName("Step_slider")
        self.gridLayout_2.addWidget(self.Step_slider, 3, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 4, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 4, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setToolTipDuration(5)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 7, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 1, 0, 1, 1)
        self.ServiceWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        value =  self.Speed_slider.value()
        self.label_5.setText("Speed val: " + str(value))
        ds.motor[4] = value
        
        value =  self.Step_slider.value()
        self.label_6.setText("Step val: " + str(value))
        ds.motor[5] = value
        
        self.pushButton.clicked.connect(lambda: ds.producer("motor"))
        self.pushButton_2.clicked.connect(lambda: ds.producer("start"))
        self.pushButton_3.clicked.connect(lambda: ds.producer("stop"))
        self.Step_slider.sliderMoved.connect(lambda: self.update_data("step"))
        self.Speed_slider.sliderMoved.connect(lambda: self.update_data("speed"))
        self.radioButton.clicked.connect(lambda: self.cheak_direction("CV"))
        self.radioButton_2.clicked.connect(lambda: self.cheak_direction("CCV"))
        
        if self.radioButton.isChecked():
            self.label_7.setText("Direction: CV")
            ds.motor[3] = 0
        else:
            self.label_7.setText("Direction: CCV")
            ds.motor[3] = 1
            
        self.retranslateUi(MainWindow)
        self.ServiceWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ServiceWidget.setTabText(self.ServiceWidget.indexOf(self.tab), _translate("MainWindow", "Devices"))
        self.label_8.setText(_translate("MainWindow", "ACC"))
        self.label_17.setText(_translate("MainWindow", "DEC"))
        self.label.setText(_translate("MainWindow", "Speed"))
        self.label_2.setText(_translate("MainWindow", "Step"))
        self.label_3.setText(_translate("MainWindow", "Direction"))
        self.radioButton.setText(_translate("MainWindow", "CV"))
        self.radioButton_2.setText(_translate("MainWindow", "CCV"))
        self.label_4.setText(_translate("MainWindow", "Current value"))
        self.label_18.setText(_translate("MainWindow", "ACC val:  0"))
        self.label_19.setText(_translate("MainWindow", "DEC val:  0"))
        self.label_5.setText(_translate("MainWindow", "Speed val:  0"))
        self.label_6.setText(_translate("MainWindow", "Step val:  0"))
        self.label_7.setText(_translate("MainWindow", "Direction:  CV"))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.ServiceWidget.setTabText(self.ServiceWidget.indexOf(self.tab_2), _translate("MainWindow", "Service"))

    def update_data(self, _str):
        match _str:
            case "speed":
                value_spd =  self.Speed_slider.value()
                self.label_5 .setText("Speed val: " + str(value_spd))
                ds.motor[4] = value_spd
            case "step":
                value_stp =  self.Step_slider.value()
                self.label_6 .setText("Step val: " + str(value_stp))
                ds.motor[5] = value_stp
                
    def cheak_direction(self, _str):
        match _str:
            case "CV":
                if self.radioButton.isChecked():
                    self.label_7.setText("Direction: CV")
                    ds.motor[3] = 0
                                    
            case "CCV":
                if self.radioButton_2.isChecked():
                    self.label_7.setText("Direction: CCV")
                    ds.motor[3] = 1
                    
