# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_11.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import data_send as ds
import data_take as dt
import time
from threading import *
import queue 
import sys

#q = queue.Queue()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Devices = QtWidgets.QTabWidget(self.centralwidget)
        self.Devices.setGeometry(QtCore.QRect(10, 0, 781, 561))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Devices.setFont(font)
        self.Devices.setObjectName("Devices")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Devices.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.change_value = QtWidgets.QLabel(self.tab_2)
        self.change_value.setGeometry(QtCore.QRect(140, 10, 95, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.change_value.setFont(font)
        self.change_value.setToolTipDuration(5)
        self.change_value.setAlignment(QtCore.Qt.AlignCenter)
        self.change_value.setObjectName("change_value")
        self.current_value = QtWidgets.QLabel(self.tab_2)
        self.current_value.setGeometry(QtCore.QRect(520, 10, 95, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_value.setFont(font)
        self.current_value.setToolTipDuration(5)
        self.current_value.setAlignment(QtCore.Qt.AlignCenter)
        self.current_value.setObjectName("current_value")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(10, 36, 751, 471))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ACC = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ACC.setFont(font)
        self.ACC.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC.setObjectName("ACC")
        self.gridLayout_2.addWidget(self.ACC, 0, 0, 1, 1)
        self.ACC_slider = QtWidgets.QSlider(self.widget)
        self.ACC_slider.setProperty("value", 25)
        self.ACC_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ACC_slider.setObjectName("ACC_slider")
        self.gridLayout_2.addWidget(self.ACC_slider, 0, 1, 1, 2)
        self.DEC = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DEC.setFont(font)
        self.DEC.setAlignment(QtCore.Qt.AlignCenter)
        self.DEC.setObjectName("DEC")
        self.gridLayout_2.addWidget(self.DEC, 1, 0, 1, 1)
        self.DEC_slider = QtWidgets.QSlider(self.widget)
        self.DEC_slider.setProperty("value", 25)
        self.DEC_slider.setOrientation(QtCore.Qt.Horizontal)
        self.DEC_slider.setObjectName("DEC_slider")
        self.gridLayout_2.addWidget(self.DEC_slider, 1, 1, 1, 2)
        self.Speed = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Speed.setFont(font)
        self.Speed.setAlignment(QtCore.Qt.AlignCenter)
        self.Speed.setObjectName("Speed")
        self.gridLayout_2.addWidget(self.Speed, 2, 0, 1, 1)
        self.Speed_slider = QtWidgets.QSlider(self.widget)
        self.Speed_slider.setProperty("value", 25)
        self.Speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_slider.setObjectName("Speed_slider")
        self.gridLayout_2.addWidget(self.Speed_slider, 2, 1, 1, 2)
        self.Step = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step.setFont(font)
        self.Step.setAlignment(QtCore.Qt.AlignCenter)
        self.Step.setObjectName("Step")
        self.gridLayout_2.addWidget(self.Step, 3, 0, 1, 1)
        self.Step_slider = QtWidgets.QSlider(self.widget)
        self.Step_slider.setProperty("value", 35)
        self.Step_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Step_slider.setObjectName("Step_slider")
        self.gridLayout_2.addWidget(self.Step_slider, 3, 1, 1, 2)
        self.irection = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.irection.setFont(font)
        self.irection.setAlignment(QtCore.Qt.AlignCenter)
        self.irection.setObjectName("irection")
        self.gridLayout_2.addWidget(self.irection, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 4, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 4, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.sendButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_3.addWidget(self.sendButton, 1, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.gridLayout_3.addWidget(self.startButton, 1, 1, 1, 1)
        self.startButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.startButton_2.setFont(font)
        self.startButton_2.setObjectName("startButton_2")
        self.gridLayout_3.addWidget(self.startButton_2, 1, 2, 1, 1)
        self.stepButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stepButton.setFont(font)
        self.stepButton.setObjectName("stepButton")
        self.gridLayout_3.addWidget(self.stepButton, 1, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.acc_val = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acc_val.setFont(font)
        self.acc_val.setAlignment(QtCore.Qt.AlignCenter)
        self.acc_val.setObjectName("acc_val")
        self.gridLayout.addWidget(self.acc_val, 0, 0, 1, 1)
        self.dec_val = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dec_val.setFont(font)
        self.dec_val.setAlignment(QtCore.Qt.AlignCenter)
        self.dec_val.setObjectName("dec_val")
        self.gridLayout.addWidget(self.dec_val, 1, 0, 1, 1)
        self.speed_val = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.speed_val.setFont(font)
        self.speed_val.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_val.setObjectName("speed_val")
        self.gridLayout.addWidget(self.speed_val, 2, 0, 1, 1)
        self.step_val = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.step_val.setFont(font)
        self.step_val.setAlignment(QtCore.Qt.AlignCenter)
        self.step_val.setObjectName("step_val")
        self.gridLayout.addWidget(self.step_val, 3, 0, 1, 1)
        self.direction_val = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.direction_val.setFont(font)
        self.direction_val.setAlignment(QtCore.Qt.AlignCenter)
        self.direction_val.setObjectName("direction_val")
        self.gridLayout.addWidget(self.direction_val, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 4)
        self.programming = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.programming.setFont(font)
        self.programming.setObjectName("programming")
        self.gridLayout_4.addWidget(self.programming, 1, 0, 1, 1)
        self.started = QtWidgets.QLabel(self.widget)
        self.started.setAlignment(QtCore.Qt.AlignCenter)
        self.started.setObjectName("started")
        self.gridLayout_4.addWidget(self.started, 1, 1, 1, 1)
        self.sucsess = QtWidgets.QLabel(self.widget)
        self.sucsess.setAlignment(QtCore.Qt.AlignCenter)
        self.sucsess.setObjectName("sucsess")
        self.gridLayout_4.addWidget(self.sucsess, 1, 2, 1, 1)
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        self.gridLayout_4.addWidget(self.error, 1, 3, 1, 1)
        self.Devices.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        value =  self.Speed_slider.value()
        self.speed_val.setText("Speed val: " + str(value))
        ds.motor[4] = value
        
        value =  self.Step_slider.value()
        self.step_val.setText("Step val: " + str(value))
        ds.motor[5] = value
        
        value =  self.ACC_slider.value()
        self.acc_val.setText("ACC val: " + str(value))
        ds.motor[1] = value
        
        value =  self.DEC_slider.value()
        self.dec_val.setText("DEC val: " + str(value))
        ds.motor[2] = value
        
        self.sendButton.clicked.connect(lambda: ds.producer("motor"))
        self.startButton.clicked.connect(lambda: ds.producer("start_run"))
        self.startButton_2.clicked.connect(lambda: ds.producer("start_move"))
        self.stepButton.clicked.connect(lambda: ds.producer("stop"))
        self.programming.clicked.connect(lambda: ds.producer("programm"))
        
        #self.programming.clicked.connect(lambda: self.thread(q))
        
        self.programming.clicked.connect(lambda: self.detect())
        self.Step_slider.sliderMoved.connect(lambda: self.update_data("step"))
        self.Speed_slider.sliderMoved.connect(lambda: self.update_data("speed"))
        self.ACC_slider.sliderMoved.connect(lambda: self.update_data("acc"))
        self.DEC_slider.sliderMoved.connect(lambda: self.update_data("dec"))
        self.radioButton.clicked.connect(lambda: self.cheak_direction("CV"))
        self.radioButton_2.clicked.connect(lambda: self.cheak_direction("CCV"))
        
        if self.radioButton.isChecked():
            self.direction_val.setText("Direction: CV")
            ds.motor[3] = 0
        else:
            self.direction_val.setText("Direction: CCV")
            ds.motor[3] = 1
            
        self.retranslateUi(MainWindow)
        self.Devices.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Devices.setTabText(self.Devices.indexOf(self.tab), _translate("MainWindow", "Devices"))
        self.change_value.setText(_translate("MainWindow", "Change value"))
        self.current_value.setText(_translate("MainWindow", "Current value"))
        self.ACC.setText(_translate("MainWindow", "ACC"))
        self.DEC.setText(_translate("MainWindow", "DEC"))
        self.Speed.setText(_translate("MainWindow", "Speed"))
        self.Step.setText(_translate("MainWindow", "Step"))
        self.irection.setText(_translate("MainWindow", "Direction"))
        self.radioButton.setText(_translate("MainWindow", "CV"))
        self.radioButton_2.setText(_translate("MainWindow", "CCV"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.startButton.setText(_translate("MainWindow", "Start (Move)"))
        self.startButton_2.setText(_translate("MainWindow", "Start (Run)"))
        self.stepButton.setText(_translate("MainWindow", "Stop"))
        #self.acc_val.setText(_translate("MainWindow", "ACC val:  0"))
        #self.dec_val.setText(_translate("MainWindow", "DEC val:  0"))
        #self.speed_val.setText(_translate("MainWindow", "Speed val:  0"))
        #self.step_val.setText(_translate("MainWindow", "Step val:  0"))
        #self.direction_val.setText(_translate("MainWindow", "Direction:  CV"))
        self.programming.setText(_translate("MainWindow", "Strat programming"))
        #self.started.setText(_translate("MainWindow", "Started"))
        #self.sucsess.setText(_translate("MainWindow", "Sucsess"))
        #self.error.setText(_translate("MainWindow", "Error"))
        self.Devices.setTabText(self.Devices.indexOf(self.tab_2), _translate("MainWindow", "Service"))



    def update_data(self, _str):
        match _str:
            case "speed":
                value_spd =  self.Speed_slider.value()
                self.speed_val .setText("Speed val: " + str(value_spd))
                ds.motor[4] = value_spd
            case "step":
                value_stp =  self.Step_slider.value()
                self.step_val .setText("Step val: " + str(value_stp))
                ds.motor[5] = value_stp
            case "acc":
                value_acc = self.ACC_slider.value()
                self.acc_val.setText("ACC val: " + str(value_acc))
                ds.motor[1] = value_acc
            case "dec":
                value_dec = self.DEC_slider.value()
                self.dec_val.setText("DEC val: " + str(value_dec))
                ds.motor[2] = value_dec
                
                
    def cheak_direction(self, _str):
        match _str:
            case "CV":
                if self.radioButton.isChecked():
                    self.direction_val.setText("Direction: CV")
                    ds.motor[3] = 0
                                    
            case "CCV":
                if self.radioButton_2.isChecked():
                    self.direction_val.setText("Direction: CCV")
                    ds.motor[3] = 1
                    
    def detect(self):
        self.started.setText("Started")
        
'''app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())'''    



